# A measurement that is useful for detecting wifi reception problems
# Make sure to set HA to retain this data for a very short time!
#
# See: https://community.home-assistant.io/t/iron-gate-sensor/97656/6
platform: wifi_signal
name: "${friendly_name} Wifi Signal"
id: ${friendly_short}_wifi_dbm
update_interval: 15s
filters:
  - sliding_window_moving_average:
      # hold 15 measurements, taken every 5 seconds
      window_size: 15
      # every 15 seconds, send the updated result..
      send_every: 15
