esphome:
  name: matrix-keyboard
  friendly_name: "Matrix Keyboard"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

matrix_keyboard:
  id: keyboard_1
  rows:
    - pin: GPIO12
    - pin: GPIO13
    - pin: GPIO14
  columns:
    - pin: GPIO25
    - pin: GPIO26
    - pin: GPIO27
    - pin: GPIO33
  keymap: "504A123B6789"
  has_diodes: True

binary_sensor:
  - platform: matrix_keyboard
    keyboard_id: keyboard_1
    name: "Switch 1"
    id: sw1
    key: 0
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 2"
    id: sw2
    key: 1
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 3"
    id: sw3
    key: 2
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 4"
    id: sw4
    key: 3
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 5"
    id: sw5
    key: 4
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 6"
    id: sw6
    key: 5
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 7"
    id: sw7
    key: 6
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 8"
    id: sw8
    key: 7
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 9"
    id: sw9
    key: 8
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 10"
    id: sw10
    key: 9
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch A"
    id: swA
    key: A
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch B"
    id: swB
    key: B
