blueprint:
  name: Control Panel LED
  description: Turn a light on based on a device state
  domain: automation
  input:
    led_color:
      name: LED On Color
      description: LED color when device is On
      selector:
        color_rgb:
    led_brightness:
      name: LED Brightness
      selector:
        number:
          max: 0
          min: 256
    panel_led:
      name: Panel LED
      description: The Light to keep in sync with the device
      selector:
        target:
          entity:
            domain: light
    target_device:
      name: Target Device
      description: The device to be synchronized with
      selector:
        entity:
          filter:
            domain: [light, switch, binary_sensor]

trigger:
  - platform: state
    entity_id: !input target_device

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input target_device
            state: "off"
        sequence:
          - service: light.turn_off
            target: !input panel_led
      - conditions:
          - condition: state
            entity_id: !input target_device
            state: "on"
        sequence:
          - service: light.turn_on
            data:
              brightness: !input led_brightness
              rgb_color: !input led_color
            target: !input panel_led
