# automations.yaml - sample control panel automations
# automations used to tie switches to devices
# These are based on the blueprint `control-panel-switch.yaml`
#
- id: '1690839798830'
  alias: Control Panel SW0 (Garage Side Light)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw0
      panel_switch: binary_sensor.control_panel_1_switch_sw0
      target_device: light.garage_side_switch
- id: '1690839798831'
  alias: Control Panel SW1 (Back Deck Light)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw1
      panel_switch: binary_sensor.control_panel_1_switch_sw1
      target_device: light.back_door_light
- id: '1690839798832'
  alias: Control Panel SW2 (Backyard/Side Light)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw2
      panel_switch: binary_sensor.control_panel_1_switch_sw2
      target_device: light.backyard_light
- id: '1690839798833'
  alias: Control Panel SW3 (Kitchen Candles)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw3
      panel_switch: binary_sensor.control_panel_1_switch_sw3
      target_device: light.kitchen_led_master
- id: '1690839798834'
  alias: Control Panel SW4 (TV Power)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw4
      panel_switch: binary_sensor.control_panel_1_switch_sw4
      target_device: switch.tv_power_strip
- id: '1690839798827'
  alias: Control Panel SW5 (Bookcase Lights)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw5
      panel_switch: binary_sensor.control_panel_1_switch_sw5
      target_device: light.bookcase_lights_2
- id: '1690839798828'
  alias: Control Panel SW6 (Reading Lamp Left)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw6
      panel_switch: binary_sensor.control_panel_1_switch_sw6
      target_device: light.reading_lamp_left
- id: '1690839798829'
  alias: Control Panel SW6 (Reading Lamp Right)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw6
      panel_switch: binary_sensor.control_panel_1_switch_sw6
      target_device: light.reading_lamp_right
- id: '1690839798837'
  alias: Control Panel SW7 (Mudroom Deck)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw7
      panel_switch: binary_sensor.control_panel_1_switch_sw7
      target_device: light.mudroom_deck_light
- id: '1690839798838'
  alias: Control Panel SW8 (Driveway Lights)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw8
      panel_switch: binary_sensor.control_panel_1_switch_sw8
      target_device: light.garage_front_switch
- id: '1690839798839'
  alias: Control Panel SW9 (Front Porch)
  description: ''
  use_blueprint:
    path: stephenhouser/control-panel-switch.yaml
    input:
      led_color:
      - 0
      - 255
      - 0
      sync_color:
      - 255
      - 0
      - 0
      led_brightness: 32
      panel_led: light.control_panel_1_light_sw9
      panel_switch: binary_sensor.control_panel_1_switch_sw9
      target_device: light.front_porch_light
