# control-panel.yaml - ESPHome configuration for the Control Panel v1
# 
# 2023/07/24 Stephen Houser
substitutions:
  device_name: "control-panel-1"
  friendly_name: "Control Panel 1"
  friendly_short: "control_panel_1"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  # Enable logger

wifi:
  # WiFi settings are mostly secrets
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # fast_connect helps with connection to hidden SSID
  fast_connect: true
  # force the network name to be on hidden network
  use_address: ${device-name}.playmates

ota:
  # Enable Over The Air (OTA) updates with password
  password: !secret ota_password

api:
  # Enable Encrypted Home Assistant API
  encryption:
    key: "G+UNlM3nwQwj87nA+e9PllL1n7BNlsvfkPNOTAX8yG0="

mqtt:
  # Secret MQTT server parameters
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password

web_server:
  # Web interface enabled and has local resources (no Internet)
  local: true
  include_internal: true

external_components:
  # use all components from a local folder
  - source:
      type: local
      path: components
    components: [ matrix_keyboard ]

globals:
  - id: led_bright
    type: int
    restore_value: yes
    initial_value: '50'

switch:
  # Allow remote restart (from web interface also)
  - platform: restart
    name: "${friendly_name} Restart"

output:
  # Configure GPIO21 as an output to pull it low and enable the rotary encoder
  # Could have just wired this to ground on the PCB, but it's wired to a pin.
  - platform: gpio
    pin: GPIO22
    id: rotarty_encoder_enable

light:
  # The Addressable RGB lights on the control panel. All in one "strip"
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO5
    id: panel_leds
    # 13 LEDs in control panel; 6 in display panel
    num_leds: 13
    rmt_channel: 0
    chipset: ws2812
    name: "Panel LEDs"

  - platform: partition
    name: "Light 0"
    id: light0
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 8
        to: 8
  - platform: partition
    name: "Light 1"
    id: light1
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 9
        to: 9
  - platform: partition
    name: "Light 2"
    id: light2
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 10
        to: 10
  - platform: partition
    name: "Light 3"
    id: light3
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 11
        to: 11
  - platform: partition
    name: "Light 4"
    id: light4
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 12
        to: 12

  - platform: partition
    name: "Light 5"
    id: light5
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 7
        to: 7
  - platform: partition
    name: "Light 6"
    id: light6
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 6
        to: 6
  - platform: partition
    name: "Light 7"
    id: light7
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 5
        to: 5
  - platform: partition
    name: "Light 8"
    id: light8
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 4
        to: 4
  - platform: partition
    name: "Light 9"
    id: light9
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 3
        to: 3

  - platform: partition
    name: "Light Encoder"
    id: light_encoder
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 2
        to: 2

  - platform: partition
    name: "Light Call"
    id: light_call
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 1
        to: 1

  - platform: partition
    name: "Light A"
    id: light_a
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 0
        to: 0
  - platform: partition
    name: "Light B"
    id: light_b
    default_transition_length: 0s
    segments:
      - id: panel_leds
        from: 0
        to: 0

matrix_keyboard:
  # The matrix toggle switches on the control panel
  # name: "Keyboard"
  id: keyboard
  rows:
    - pin: GPIO12
    - pin: GPIO13
    - pin: GPIO14
  columns:
    - pin: GPIO25
    - pin: GPIO26
    - pin: GPIO27
    - pin: GPIO33
  # The PCB was laid out to make the wires go, so the rows and columns
  # are not really lined up. This mapping maps the switches to sane "keys"
  keymap: "504A123B6789"
  # There are diodes for n-key rollover
  has_diodes: true     

binary_sensor:
  - <<: !include common/status.yaml

  # The red call pushbutton
  - platform: gpio
    name: "Call Button"
    id: call_button
    pin: 
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.turn_on:
            id: light_call
            brightness: !lambda |-
              return id(led_bright) / 100.0;
            red: 1
            green: 0
            blue: 0
            white: 0
    on_release:
      then:
        - light.turn_off: light_call

  # The rotary encoder has a push button
  - platform: gpio
    name: "Rotary Encoder Button"
    id: rotary_encoder_button
    pin: 
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - light.turn_on:
            id: light_encoder
            brightness: !lambda |-
              return id(led_bright) / 100.0;
            red: 1
            green: 0
            blue: 0
            white: 0
    on_release:
      then:
        - light.turn_off: light_encoder

  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 0"
    id: sw0
    key: 0
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 1"
    id: sw1
    key: 1
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 2"
    id: sw2
    key: 2
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 3"
    id: sw3
    key: 3
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 4"
    id: sw4
    key: 4

  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 5"
    id: sw5
    key: 5
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 6"
    id: sw6
    key: 6
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 7"
    id: sw7
    key: 7
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 8"
    id: sw8
    key: 8
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch 9"
    id: sw9
    key: 9

  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch A"
    id: swA
    key: A
  - platform: matrix_keyboard
    keyboard_id: keyboard
    name: "Switch B"
    id: swB
    key: B

sensor:
  - <<: !include common/wifi_status.yaml
  - <<: !include common/uptime.yaml
  # The rotary encoder rotation
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: panel_encoder
    publish_initial_value: True
    pin_a: 
      number: GPIO21
      mode: INPUT_PULLUP
    pin_b: 
      number: GPIO23
      mode: INPUT_PULLUP
    on_clockwise:
      then:
        - lambda: !lambda |-
            int bright = id(led_bright) < 100 ? id(led_bright) + 1 : 100;
            id(led_bright) = bright;
    on_anticlockwise:
      then:
        - lambda: !lambda |-
            int bright = id(led_bright) > 0 ? id(led_bright) - 1 : 0;
            id(led_bright) = bright;
