# control-panel.yaml - ESPHome configuration for the Control Panel v1
# 
# 2023/07/24 Stephen Houser
substitutions:
  device_name: "dev-sound"
  friendly_name: "Dev Sound"
  friendly_short: "dev_sound"

esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

logger:
  # Enable logger

wifi:
  # WiFi settings are mostly secrets
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # fast_connect helps with connection to hidden SSID
  fast_connect: True
  # force the network name to be on hidden network
  use_address: ${device_name}.playmates

ota:
  # Enable Over The Air (OTA) updates with password
  password: !secret ota_password

api:
  # Enable Encrypted Home Assistant API
  encryption:
    key: "G+UNlM3nwQwj87nA+e9PllL1n7BNlsvfkPNOTAX8yG0="

# mqtt:
#   # Secret MQTT server parameters
#   broker: !secret mqtt_host
#   username: !secret mqtt_user
#   password: !secret mqtt_password

web_server:
  # Web interface enabled and has local resources (no Internet)
  local: True
  include_internal: True

switch:
  # Allow remote restart (from web interface also)
  - platform: restart
    name: "${friendly_name} Restart"

# speaker:
#   - platform: i2s_audio
#     dac_tpye: external
#     i2s_dout_pin: GPIO16
#     mode: mono

i2s_audio:
  i2s_lrclk_pin: GPIO26
  i2s_bclk_pin: GPIO27

media_player:
  - platform: i2s_audio
    name: media player
    dac_type: external
    i2s_dout_pin: GPIO14
    mode: mono
