input_select:
  dev_control_panel_display:
    name: Dev Control Panel Display
    options:
      - HVAC
      - Power
      - Temperature
    initial: Power

template:
  - sensor:
      - name: "Dev Control Panel Display A"
        unique_id: "102010"
        icon: mdi:clock-digital
        state: >
          {% if is_state('input_select.dev_control_panel_display', 'HVAC') %}
            {{ states('sensor.furnace_temperature') | int | string }}
          {% elif is_state('input_select.dev_control_panel_display', 'Power') %}
            time
          {% elif is_state('input_select.dev_control_panel_display', 'Temperature') %}
            {{ states('sensor.temperature') | int | string }}
          {% else %}
            {{ none }}
          {% endif %}

      - name: "Dev Control Panel Display B"
        unique_id: "102011"
        icon: mdi:clock-digital
        state: >
          {% if is_state('input_select.dev_control_panel_display', 'HVAC') %}
            {{ states('sensor.heating_oil') | int }}
          {% elif is_state('input_select.dev_control_panel_display', 'Power') %}
            {{ states('sensor.mains') | int }}
          {% elif is_state('input_select.dev_control_panel_display', 'Temperature') %}
            {{ states('sensor.inside_temperature') | int }}
          {% else %}
            {{ none }}
          {% endif %}

automation:
  - id: "2690839798830"
    alias: Dev Control Panel SW0 (Garage Side Light)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw0
        panel_switch: binary_sensor.dev_control_panel_switch_sw0
        target_device: light.garage_side_switch
  - id: "2690839798831"
    alias: Dev Control Panel SW1 (Back Deck Light)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw1
        panel_switch: binary_sensor.dev_control_panel_switch_sw1
        target_device: light.back_door_light
  - id: "2690839798832"
    alias: Dev Control Panel SW2 (Backyard/Side Light)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw2
        panel_switch: binary_sensor.dev_control_panel_switch_sw2
        target_device: light.backyard_light
  - id: "2690839798833"
    alias: Dev Control Panel SW3 (Kitchen Candles)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw3
        panel_switch: binary_sensor.dev_control_panel_switch_sw3
        target_device: light.kitchen_led_master
  - id: "2690839798834"
    alias: Dev Control Panel SW4 (TV Power)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw4
        panel_switch: binary_sensor.dev_control_panel_switch_sw4
        target_device: switch.tv_power_strip
  - id: "2690839798827"
    alias: Dev Control Panel SW5 (Bookcase Lights)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw5
        panel_switch: binary_sensor.dev_control_panel_switch_sw5
        target_device: light.bookcase_lights_2
  - id: "2690839798828"
    alias: Dev Control Panel SW6 (Reading Lamp Left)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw6
        panel_switch: binary_sensor.dev_control_panel_switch_sw6
        target_device: light.reading_lamp_left
  - id: "2690839798829"
    alias: Dev Control Panel SW6 (Reading Lamp Right)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw6
        panel_switch: binary_sensor.dev_control_panel_switch_sw6
        target_device: light.reading_lamp_right
  - id: "2690839798837"
    alias: Dev Control Panel SW7 (Mudroom Deck)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw7
        panel_switch: binary_sensor.dev_control_panel_switch_sw7
        target_device: light.mudroom_deck_light
  - id: "2690839798838"
    alias: Dev Control Panel SW8 (Driveway Lights)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-switch.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw8
        panel_switch: binary_sensor.dev_control_panel_switch_sw8
        target_device: light.garage_front_switch
  - id: "2690839798839"
    alias: Dev Control Panel SW9 (Front Porch)
    description: ""
    use_blueprint:
      path: stephenhouser/control-panel-event.yaml
      input:
        led_color:
          - 0
          - 255
          - 0
        sync_color:
          - 255
          - 0
          - 0
        led_brightness: 32
        panel_led: light.dev_control_panel_led_sw9
        panel_switch: binary_sensor.dev_control_panel_switch_sw9
  - id: "2690841637084"
    alias: Dev Call Button
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.dev_control_panel_call_button
        to: "on"
    condition: []
    action:
      - service: light.toggle
        data:
          color_name: fuchsia
          brightness: 32
        target:
          entity_id: light.dev_control_panel_led_call
    mode: single
  - id: "2691187239105"
    alias: Dev Control Panel SWAB
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.dev_control_panel_switch_swa
          - binary_sensor.dev_control_panel_switch_swb
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.dev_control_panel_switch_swa
                state: "on"
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 246
                    - 97
                    - 81
                  brightness: 32
                target:
                  entity_id: light.dev_control_panel_led_swab
              - service: input_select.select_option
                data:
                  option: HVAC
                target:
                  entity_id: input_select.dev_control_panel_display
          - conditions:
              - condition: state
                entity_id: binary_sensor.dev_control_panel_switch_swb
                state: "on"
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 143
                    - 240
                    - 164
                  brightness: 29
                target:
                  entity_id: light.dev_control_panel_led_swab
              - service: input_select.select_option
                data:
                  option: Temperature
                target:
                  entity_id: input_select.dev_control_panel_display
          - conditions: []
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.dev_control_panel_led_swab
              - service: input_select.select_option
                data:
                  option: Power
                target:
                  entity_id: input_select.dev_control_panel_display
    mode: single
  - id: "2690842053154"
    alias: Dev Office Light Toggle
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.dev_control_panel_rotary_encoder_button
        to: "on"
    condition: []
    action:
      - service: light.toggle
        target:
          entity_id: light.office_bookcase
        data: {}
      - service: light.toggle
        target:
          entity_id: light.dev_control_panel_led_encoder
        data:
          rgb_color:
            - 0
            - 255
            - 0
          brightness: 32
    mode: single
  - id: "2690842053155"
    alias: Dev Office Light Effect
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.dev_control_panel_rotary_encoder
    condition:
      - condition: state
        entity_id: light.office_bookcase
        state: "on"
    action:
      - service: light.turn_on
        data:
          effect:
            "{{ state_attr('light.office_bookcase', 'effect_list')[ states.sensor.control_panel_1_rotary_encoder.state
            % 188 ] }}"
        target:
          entity_id: light.office_bookcase
    mode: single
